name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -i keyfile ubuntu@ec2-52-66-199-67.ap-south-1.compute.amazonaws.com
        export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v20.5.0/bin
        cd deploy
        git pull origin master
        pm2 kill
        pm2 start index.js